name: movie
description: A new Flutter package project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.3
  core:
    path: ../core
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  sqflite: ^2.2.0+3
  flutter_bloc: ^8.1.1
  flutter_rating_bar: ^4.0.1
  get_it: ^7.2.0
  http: ^0.13.5
  path_provider: ^2.0.11

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.2

# The following section is specific to Flutter packages.
flutter:
